// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhoauhbplvlutywbtnjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJob2F1aGJwbHZsdXR5d2J0bmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDM1MjksImV4cCI6MjA2NTExOTUyOX0.Dg8UcvN9dES6af-Coea_VYu-2UBdy-mM0DK54_8B7Yk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);